# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ogn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AircraftPos(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 32

    # AircraftPos
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AircraftPos
    def Callsign(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # AircraftPos
    def Timestamp(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # AircraftPos
    def Type(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # AircraftPos
    def Stealth(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(9))
    # AircraftPos
    def Notrack(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
    # AircraftPos
    def Heading(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # AircraftPos
    def Speed(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # AircraftPos
    def Lat(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))
    # AircraftPos
    def Lon(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))
    # AircraftPos
    def Alt(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(28))

def CreateAircraftPos(builder, callsign, timestamp, type, stealth, notrack, heading, speed, lat, lon, alt):
    builder.Prep(4, 32)
    builder.PrependInt32(alt)
    builder.PrependFloat32(lon)
    builder.PrependFloat32(lat)
    builder.PrependInt32(speed)
    builder.PrependInt32(heading)
    builder.Pad(1)
    builder.PrependBool(notrack)
    builder.PrependBool(stealth)
    builder.PrependInt8(type)
    builder.PrependInt32(timestamp)
    builder.PrependInt32(callsign)
    return builder.Offset()
