# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ogn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OneMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OneMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOneMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OneMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OneMessage
    def AircPos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from ogn.AircraftPos import AircraftPos
            obj = AircraftPos()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OneMessage
    def GrouPos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from ogn.GroundPos import GroundPos
            obj = GroundPos()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OneMessage
    def GrouSta(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from ogn.GroundStat import GroundStat
            obj = GroundStat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(3)
def OneMessageStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddAircPos(builder, aircPos): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(aircPos), 0)
def OneMessageAddAircPos(builder, aircPos):
    """This method is deprecated. Please switch to AddAircPos."""
    return AddAircPos(builder, aircPos)
def AddGrouPos(builder, grouPos): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(grouPos), 0)
def OneMessageAddGrouPos(builder, grouPos):
    """This method is deprecated. Please switch to AddGrouPos."""
    return AddGrouPos(builder, grouPos)
def AddGrouSta(builder, grouSta): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(grouSta), 0)
def OneMessageAddGrouSta(builder, grouSta):
    """This method is deprecated. Please switch to AddGrouSta."""
    return AddGrouSta(builder, grouSta)
def End(builder): return builder.EndObject()
def OneMessageEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)