/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4-dev */

#include "ogn_service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(type_4, type_4, AUTO)


PB_BIND(type_5, type_5, AUTO)


PB_BIND(FanetService, FanetService, AUTO)


PB_BIND(ReceiverConfiguration, ReceiverConfiguration, AUTO)


PB_BIND(OneMessage, OneMessage, AUTO)
